FROM python:3.9.14

WORKDIR /app

RUN apt-get update \
    && apt-get install -y \
        unzip \
        wget \
    && rm -rf /var/lib/apt/lists/*

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip \
    && unzip terraform_1.0.0_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_1.0.0_linux_amd64.zip

CMD ["tail", "-f", "/dev/null"]