services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: backend-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      -  .env
    volumes:
      - mongodb-data:/data/db
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongodb-data: