name: cd-to-preprod

on:
  push:
    branches:
      - add-config-for-cd 

jobs:
  continuous-integration-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Create .env file
        run: |
          echo "RAPID_API_URL=$RAPID_API_URL" >> .env
          echo "RAPID_API_HOST=$RAPID_API_HOST" >> .env
          echo "RAPID_API_KEY=$RAPID_API_KEY" >> .env
          echo "MONGO_DB_URL=$MONGO_DB_URL" >> .env
          echo "MONGO_DB_DATABASE=$MONGO_DB_DATABASE" >> .env
          echo "MONGO_DB_COLLECTION=$MONGO_DB_COLLECTION" >> .env
          echo "FRONTEND_URL=$FRONTEND_URL" >> .env
        env:
          RAPID_API_URL: ${{ secrets.RAPID_API_URL }}
          RAPID_API_HOST: ${{ secrets.RAPID_API_HOST }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          MONGO_DB_DATABASE: ${{ secrets.MONGO_DB_DATABASE }}
          MONGO_DB_COLLECTION: ${{ secrets.MONGO_DB_COLLECTION }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Install dependencies
        run: |
          docker-compose exec -T app poetry install

      - name: Static analysis
        run: |
          docker-compose exec -T app poetry run autoflake --remove-all-unused-imports --remove-unused-variables --recursive --in-place . --exclude=__init__.py,venv,.venv
          docker-compose exec -T app poetry run black adapters/ api/ core/ factories/
          docker-compose exec -T app poetry run isort adapters/ api/ core/ factories/
          docker-compose exec -T app poetry run flake8 adapters/ api/ core/ factories/ 

      - name: Test with pytest and coverage
        run: |
          docker-compose exec -T app poetry run coverage run -m pytest
          docker-compose exec -T app poetry run coverage report -m

      - name: Shut down Docker Compose
        run: |
          docker-compose -f docker-compose.yml down